# Generated by Django 4.1.2 on 2022-11-06 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('apt', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_first_name', models.CharField(max_length=255)),
                ('st_last_name', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=255)),
                ('pr_first_name', models.CharField(max_length=255)),
                ('pr_last_name', models.CharField(max_length=255)),
                ('phone_number_one', models.CharField(max_length=12)),
                ('phone_number_two', models.CharField(max_length=12)),
                ('emr_first_name', models.CharField(max_length=255)),
                ('emr_last_name', models.CharField(max_length=255)),
                ('emr_phone_number', models.CharField(max_length=12)),
                ('relation', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('student_first_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('grade_level', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four')], default='Select Your Level', max_length=255)),
                ('parents_first_name', models.CharField(max_length=255, null=True)),
                ('parents_last_name', models.CharField(max_length=255, null=True)),
                ('parent_phone_one', models.CharField(max_length=13)),
                ('parent_phone_two', models.CharField(max_length=13)),
                ('emergency_person_first_name', models.CharField(max_length=255)),
                ('emergency_person_last_name', models.CharField(max_length=255)),
                ('emergency_person_phone_two', models.CharField(max_length=13)),
                ('emergency_person_relation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=0)),
                ('price', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=255)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.session')),
            ],
        ),
    ]
