# Generated by Django 4.1.2 on 2022-11-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(default='1 hr', max_length=20),
        ),
    ]
