# Generated by Django 4.1.2 on 2023-01-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='servicessale',
            old_name='total',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='servicessale',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.event'),
            preserve_default=False,
        ),
    ]
