# Generated by Django 4.1.2 on 2023-01-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='label',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='servicessale',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='myapp.event'),
        ),
    ]
