# Generated by Django 4.1.2 on 2023-01-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_label_session_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicessale",
            name="status",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicessale",
            name="transaction_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
