# Generated by Django 4.1.2 on 2023-01-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_servicessale_status_servicessale_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "INITIATED"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="INITIATED",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="servicessale",
            name="status",
        ),
        migrations.RemoveField(
            model_name="servicessale",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="servicessale",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="myapp.transaction",
            ),
            preserve_default=False,
        ),
    ]
