# Generated by Django 4.1.2 on 2023-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_transaction_remove_servicessale_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("PRODUCTS", "PRODUCTS"), ("SERVICES", "SERVICES")],
                default="SERVICES",
                max_length=255,
            ),
        ),
    ]
