# Generated by Django 4.1.2 on 2023-01-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_transaction",
                to="myapp.transaction",
            ),
            preserve_default=False,
        ),
    ]
