# Generated by Django 4.1.2 on 2023-01-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_productsale_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "INITIATED"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="INITIATED",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "INITIATED"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="INITIATED",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productsale",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_transaction",
                to="myapp.producttransaction",
            ),
        ),
        migrations.AlterField(
            model_name="servicessale",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="myapp.servicetransaction",
            ),
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
