# Generated by Django 4.1.5 on 2023-01-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_producttransaction_servicetransaction_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttransaction",
            old_name="status",
            new_name="payment_status",
        ),
        migrations.RenameField(
            model_name="servicetransaction",
            old_name="status",
            new_name="payment_status",
        ),
    ]
