# Generated by Django 4.1.5 on 2023-02-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsale",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="myapp.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsale",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
