# Generated by Django 4.1.2 on 2023-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productsale_product_productsale_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
            ],
        ),
    ]
