# Generated by Django 4.1.2 on 2023-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_yelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelp',
            name='rating',
            field=models.FloatField(),
        ),
    ]
