# Generated by Django 4.1.2 on 2023-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_yelp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicessale',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
